### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by elsa-1920** [srihari-humbarwadi/retinanet-tensorflow2.x#3]
**I'm** curiose to know..... Do you believe in documentation?
nice topice! nice results! no doc to run!

**Comment by srihari-humbarwadi** [comment]
@elsa-1920  Thanks for pointing out, I forgot to put the WIP tag and I have paused working on this repository. There are a couple of things i would be adding like documentation and evaluation scripts. Please check back in a few weeks!

**Comment by elsa-1920** [comment]
thx
