### ISSUE TITLE
MAP for evaluation

### ISSUE THREAD

**Issue by oarriaga** [srihari-humbarwadi/retinanet-tensorflow2.x#4]
Hi! we have programmed some time ago a callback for MAP evaluation. It should work for any dataset as long as inputs and outputs match:

https://github.com/oarriaga/paz/blob/3a59d68e51e1cdd1b2131ca62e53b36369f14b9c/paz/optimization/callbacks.py#L86

Also feel free to contact me if you would like to collaborate :)  Cheers.

**Comment by srihari-humbarwadi** [comment]
@oarriaga Thank you for letting me know about this, looks interesting!
Have you by any chance checked the compatibility with *Cloud TPUs* ?, I did not happen to go through or run the code on *TPUs*
